---
title: "ANA515_Assignment1"
author: "Peide Liu"
date: "6/5/2022"
output: html_document
theme: bootswatch:Cyborg


      
---

#```{r setup, include=FALSE}
#knitr::opts_chunk$set(echo = TRUE)
#```

install.packages("tidyverse")

```{r setup, include = FALSE}

  library(ggplot2)
  library(dplyr)
  library(tidyverse)
  library(knitr)
  library(bslib)
```


```{r, echo= TRUE }
url<-"https://raw.githubusercontent.com/fivethirtyeight/guns-data/master/full_data.csv"
gun_deaths<-read.csv(url)
```

```{r, echo = TRUE}
##create a subset of gun_deaths
youth<-gun_deaths %>%
  filter(age <= 65)
```

```{r, echo = TRUE}
summary(youth)
```

we have data about`r nrow(gun_deaths)`individuals killed by guns. 
Only`r nrow(gun_deaths) - nrow(youth)`are older than 65. 
The distrubution of the remainder is shown below:
  
    
#Gun deaths by age
```{r youth-dist, echo = TRUE}
youth %>%
  ggplot(aes(age))+ geom_freqpoly(binwidth = 1)
```

#Gun death by race
```{r race-dist,echo = TRUE}
youth %>%
  ggplot(aes(fct_infreq(race)%>%fct_rev()))+geom_bar() + coord_flip() +
  labs(x = "Victim race")
```

# ``` {r race-dist,  echo = TRUE}
# #This next code chunk will make a plot for the distribution of youth by race
# youth%>%ggplot(aes(fct_infreq(race)%>%fct_rev()))+
#   geom_bar() + coord_flip() + labs(x = "Victim race")
# ```

